CREATE TABLE IF NOT EXISTS vehicles
    (id INT IDENTITY,
     year SMALLINT NOT NULL,
     make VARCHAR(20) NOT NULL,
     model VARCHAR(50) NOT NULL,
     comment VARCHAR(1000),
     price DECIMAL (12, 4) NOT NULL DEFAULT 0)